# Generated by Django 5.2.7 on 2025-10-06 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_departement', models.CharField(max_length=50, unique=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('matricule', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=30)),
                ('sexe', models.CharField(max_length=1)),
                ('date_naissance', models.DateField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('telephone', models.CharField(max_length=9)),
                ('adresse', models.CharField(default='Non renseignée', max_length=255)),
                ('date_embauche', models.DateField()),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='gestion_rh.departement')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='gestion_rh.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField(default='Vacances annuelles', max_length=500)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En Attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='gestion_rh.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_formation', models.CharField(max_length=100)),
                ('organisme', models.CharField(max_length=100)),
                ('date_formation', models.DateField()),
                ('personnel_suivi', models.ManyToManyField(blank=True, related_name='formations_suivies', to='gestion_rh.employe')),
            ],
        ),
        migrations.CreateModel(
            name='JourDeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=50)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('statut', models.CharField(max_length=50)),
                ('employes', models.ManyToManyField(blank=True, related_name='horaires', to='gestion_rh.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste_recherche', models.CharField(max_length=20)),
                ('date_debut_recrutement', models.DateField()),
                ('date_fin_recrutement', models.DateField()),
                ('candidats_postulants', models.ManyToManyField(blank=True, related_name='postulations', to='gestion_rh.candidat')),
                ('employe_recruteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recrutements_geres', to='gestion_rh.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_effective', models.DateField(blank=True, null=True)),
                ('periode', models.CharField(default='Mensuel', max_length=50)),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='gestion_rh.employe')),
            ],
        ),
    ]
