# Generated by Django 5.2.7 on 2025-10-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recrutement',
            name='candidats_postulants',
        ),
        migrations.RemoveField(
            model_name='recrutement',
            name='employe_recruteur',
        ),
        migrations.DeleteModel(
            name='Candidat',
        ),
        migrations.DeleteModel(
            name='Recrutement',
        ),
    ]
