# Generated by Django 5.2.7 on 2025-10-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rh', '0002_remove_recrutement_candidats_postulants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conge',
            options={'verbose_name': 'Congé', 'verbose_name_plural': 'Congés'},
        ),
        migrations.AlterModelOptions(
            name='contrat',
            options={'verbose_name': 'Contrat', 'verbose_name_plural': 'Contrats'},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='jourdetravail',
            options={'verbose_name': 'Jour de Travail', 'verbose_name_plural': 'Jours de Travail'},
        ),
        migrations.AlterModelOptions(
            name='salaire',
            options={'ordering': ['-date_effective'], 'verbose_name': 'Salaire', 'verbose_name_plural': 'Salaires'},
        ),
        migrations.AddField(
            model_name='formation',
            name='cout',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('STAGE', 'Stage')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jourdetravail',
            name='statut',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
