# Generated by Django 5.1.3 on 2025-10-19 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI - Contrat à durée indéterminée'), ('CDD', 'CDD - Contrat à durée déterminée'), ('STAGE', 'Stage'), ('INTERIM', 'Intérim'), ('APPRENTISSAGE', 'Apprentissage'), ('VACATAIRE', 'Vacataire'), ('PRESTATAIRE', 'Prestataire'), ('CONSULTANT', 'Consultant')], max_length=15, verbose_name='Type de contrat'),
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du département')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('budget_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget annuel')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_diriges', to='rh_app.employe', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='employe',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='rh_app.departement', verbose_name='Département'),
        ),
        migrations.CreateModel(
            name='DossierPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CONTRAT', 'Contrat de travail'), ('CV', 'CV'), ('DIPLOME', 'Diplôme'), ('CERTIFICAT', 'Certificat'), ('EVALUATION', 'Évaluation'), ('SANCTION', 'Sanction'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de document')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('document', models.FileField(upload_to='dossiers_personnel/', verbose_name='Document')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('confidentiel', models.BooleanField(default=False, verbose_name='Confidentiel')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='rh_app.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Dossier personnel',
                'verbose_name_plural': 'Dossiers personnels',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='JourTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heures_travaillees', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Heures travaillées')),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Heures supplémentaires')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jours_travail', to='rh_app.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Jour de travail',
                'verbose_name_plural': 'Jours de travail',
                'ordering': ['-date'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
