# Generated by Django 5.1.3 on 2025-10-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_app', '0003_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'CDI - Contrat à durée indéterminée'), ('CDD', 'CDD - Contrat à durée déterminée'), ('VACATAIRE', 'Vacataire'), ('PRESTATAIRE', 'Prestataire')], max_length=15, verbose_name='Type de contrat'),
        ),
    ]
