# Generated by Django 5.2.3 on 2025-10-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_app', '0004_alter_contrat_type_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='type_conge',
            field=models.CharField(choices=[('ANNUEL', 'Congé annuel'), ('MALADIE', 'Congé maladie'), ('MATERNITE', 'Congé maternité'), ('PATERNITE', 'Congé paternité'), ('SANS_SOLDE', 'Congé sans solde'), ('SPECIAL', 'Congé spécial'), ('FORMATION', 'Congé formation'), ('EXCEPTIONNEL', 'Congé exceptionnel'), ('FAMILIAL', 'Congé familial'), ('MISSION', 'Congé pour mission'), ('SEMINAIRE', 'Congé séminaire'), ('ETUDE', "Congé d'étude"), ('ADMINISTRATIF', 'Congé administratif'), ('DEUIL', 'Congé deuil'), ('MARIAGE', 'Congé mariage'), ('NAISSANCE', 'Congé naissance'), ('ACCIDENT', 'Congé accident du travail'), ('REPOS', 'Congé de repos compensateur'), ('SANTE', 'Congé pour raisons de santé'), ('SABBATIQUE', 'Congé sabbatique'), ('AUTRE', 'Autre')], max_length=15, verbose_name='Type de congé'),
        ),
    ]
